// The election map's data file (docs/sweden/sweden-data.wgsl, generated by
// docs/sweden/sweden-election.ts) holds a run-length raster, a word per municipality and a marker
// per municipality that sweden.wgsl decodes by hand. These read the generated text back
// and check the arithmetic both sides rely on: every row's runs cover exactly the grid's
// width, every run names a municipality the table has, every word decodes to a party and
// a share that make sense, every municipality has one marker on its own land with the
// band index finding it and a stack of every party in order, and the projection puts
// Stockholm where Stockholm is.

import { compileShader } from "../gpu/shader.ts";
import { worldSources } from "../sdf/sources.ts";
import { DEFAULT_SKY, SKIES } from "../render/sky.ts";

const DATA = Deno.readTextFileSync("docs/sweden/sweden-data.wgsl");
const WORLD = Deno.readTextFileSync("docs/sweden/sweden.wgsl");

function assert(cond: boolean, what: string): void {
  if (!cond) throw new Error(what);
}

function constant(name: string): number {
  const m = DATA.match(new RegExp(`const ${name}: (?:f32|i32|u32) = (-?[0-9.]+)u?;`));
  assert(m !== null, `${name} is missing`);
  return parseFloat(m![1]);
}

function array(name: string): number[] {
  const m = DATA.match(new RegExp(`const ${name} = array<u32, (\\d+)>\\(([^)]*)\\);`));
  assert(m !== null, `${name} is missing`);
  const words = m![2].split(",").map((s) => s.trim()).filter((s) => s !== "").map((s) => parseInt(s, 10));
  assert(words.length === parseInt(m![1], 10), `${name} declares ${m![1]} words and holds ${words.length}`);
  return words;
}

const COLS = constant("SWEDEN_COLS");
const ROWS = constant("SWEDEN_ROWS");
const MUNIS = constant("SWEDEN_MUNIS");
const PARTIES = constant("SWEDEN_PARTIES");
const BAND_ROWS = constant("SWEDEN_BAND_ROWS");
const BANDS = constant("SWEDEN_BANDS");
const ROW_START = array("SWEDEN_ROW_START");
const RUNS = array("SWEDEN_RUNS");
const MUNI = array("SWEDEN_MUNI");
const MARKERS = array("SWEDEN_MARKERS");
const BAND_START = array("SWEDEN_BAND_START");
const VOTES = array("SWEDEN_VOTES");
const STACK_WORDS = constant("SWEDEN_STACK_WORDS");
const STACK = array("SWEDEN_STACK");

Deno.test("every row's runs cover the grid's width and name a municipality the table has", () => {
  assert(ROW_START.length === ROWS + 1, `${ROW_START.length} row starts for ${ROWS} rows`);
  assert(ROW_START[ROWS] === RUNS.length, "the last row start is not the end of the runs");
  for (let r = 0; r < ROWS; r++) {
    assert(ROW_START[r] < ROW_START[r + 1], `row ${r} has no runs`);
    let width = 0;
    for (let i = ROW_START[r]; i < ROW_START[r + 1]; i++) {
      const muni = RUNS[i] & 0x1ff;
      const length = RUNS[i] >>> 9;
      assert(muni <= MUNIS, `row ${r} names municipality ${muni} of ${MUNIS}`);
      assert(length > 0 && length <= 255, `row ${r} has a run of ${length}`);
      width += length;
    }
    assert(width === COLS, `row ${r} covers ${width} cells of ${COLS}`);
  }
});

Deno.test("every municipality word decodes to a party, a share and a county that make sense", () => {
  assert(MUNI.length === MUNIS, `${MUNI.length} words for ${MUNIS} municipalities`);
  assert(MUNI.length === 290, "Sweden has 290 municipalities");
  const used = new Set<number>();
  for (const i of RUNS.map((w) => w & 0x1ff)) if (i > 0) used.add(i - 1);
  const counties = new Set<number>();
  for (let i = 0; i < MUNI.length; i++) {
    const party = MUNI[i] & 0xf;
    const share = ((MUNI[i] >>> 4) & 0x3ff) / 10;
    const turnout = ((MUNI[i] >>> 14) & 0x3ff) / 10;
    const county = (MUNI[i] >>> 24) & 0x1f;
    assert(party < PARTIES, `municipality ${i} was won by party ${party}`);
    assert(share > 15 && share < 70, `municipality ${i} was won with ${share}%`);
    assert(turnout > 50 && turnout <= 100, `municipality ${i} has a turnout of ${turnout}%`);
    assert(county >= 1 && county <= 25, `municipality ${i} is in county ${county}`);
    counties.add(county);
  }
  assert(counties.size === 21, `${counties.size} counties, not 21`);
  // Every municipality is on the map somewhere: a polygon too small for a 4 km cell
  // would vanish, so the generator gives it the cell its centre is in.
  const off = [...Array(MUNI.length).keys()].filter((i) => !used.has(i));
  assert(off.length === 0, `municipalities with no cell on the map: ${off.join(", ")}`);
});

// The same lookup sweden.wgsl does, in TypeScript.
function muniAt(col: number, row: number): number {
  if (col < 0 || row < 0 || col >= COLS || row >= ROWS) return 0;
  let x = 0;
  for (let i = ROW_START[row]; i < ROW_START[row + 1]; i++) {
    x += RUNS[i] >>> 9;
    if (col < x) return RUNS[i] & 0x1ff;
  }
  return 0;
}

Deno.test("every municipality has one marker, on its own land, that its band finds", () => {
  assert(MARKERS.length === MUNIS, `${MARKERS.length} markers for ${MUNIS} municipalities`);
  assert(BAND_START.length === BANDS + 1, `${BAND_START.length} band starts for ${BANDS} bands`);
  assert(BAND_START[BANDS] === MARKERS.length, "the last band start is not the end of the markers");
  assert(Math.ceil(ROWS / BAND_ROWS) === BANDS, "the bands do not cover the rows");
  const seen = new Set<number>();
  let lastRow = -1;
  for (let i = 0; i < MARKERS.length; i++) {
    const muni = MARKERS[i] & 0x1ff;
    const col = (MARKERS[i] >>> 9) & 0xff;
    const row = (MARKERS[i] >>> 17) & 0x1ff;
    assert(!seen.has(muni), `municipality ${muni} has two markers`);
    seen.add(muni);
    assert(muniAt(col, row) === muni + 1, `marker ${i} stands on municipality ${muniAt(col, row) - 1}, not ${muni}`);
    assert(row >= lastRow, "markers are not in row order");
    lastRow = row;
    const band = Math.floor(row / BAND_ROWS);
    assert(BAND_START[band] <= i && i < BAND_START[band + 1], `marker ${i} in row ${row} is outside band ${band}`);
  }
  assert(seen.size === MUNIS, "a municipality has no marker");
});

Deno.test("every stack lists every party once, biggest share first, and its votes are the municipality's", () => {
  assert(VOTES.length === MUNIS, `${VOTES.length} vote counts for ${MUNIS} municipalities`);
  assert(STACK.length === MUNIS * STACK_WORDS, `${STACK.length} stack words for ${MUNIS} municipalities`);
  const PARTY_MAX = 10.0; // the world's BUBBLE_MAX in voxels, which no bubble may reach
  for (let i = 0; i < MUNIS; i++) {
    assert(VOTES[i] > 1000 && VOTES[i] < 1_000_000, `municipality ${i} cast ${VOTES[i]} votes`);
    const parties = new Set<number>();
    let last = Infinity;
    let total = 0;
    for (let k = 0; k < STACK_WORDS * 2; k++) {
      const word = STACK[i * STACK_WORDS + (k >>> 1)];
      const entry = (k & 1) === 1 ? word >>> 16 : word & 0xffff;
      const party = entry & 7;
      const share = (entry >>> 3) / 10;
      assert(!parties.has(party), `municipality ${i} lists party ${party} twice`);
      parties.add(party);
      assert(share <= last, `municipality ${i}'s stack is not in order of share`);
      last = share;
      total += share;
      const radius = 0.8 + Math.sqrt((VOTES[i] * share) / 100 / 3600);
      assert(radius < PARTY_MAX, `municipality ${i}, party ${party}: a bubble of radius ${radius.toFixed(1)}`);
    }
    assert(parties.size === PARTIES, `municipality ${i} lists ${parties.size} parties`);
    assert(total > 90 && total <= 100.5, `municipality ${i}'s shares sum to ${total.toFixed(1)}%`);
    const winner = MUNI[i] & 0xf;
    const first = STACK[i * STACK_WORDS] & 7;
    assert(first === winner, `municipality ${i}'s stack starts with party ${first}, the winner is ${winner}`);
  }
});

// The world is not in WORLDS, so the voxelizer test that compiles every world does not
// see it; its page builds it from these two files through the API, and this holds them
// to the engine's contract the same way (skipped without an adapter).
Deno.test("the election world compiles against the engine's block constants and library", async () => {
  const adapter = await navigator.gpu?.requestAdapter();
  if (!adapter) {
    console.log("no WebGPU adapter in this Deno; skipping");
    return;
  }
  const device = await adapter.requestDevice();
  const errors: string[] = [];
  const sources = worldSources({ name: "sweden", code: DATA + WORLD, seed: 1, spawn: [0, 0, 0], sky: SKIES[DEFAULT_SKY] });
  const module = await compileShader(device, "sweden", [...sources, {
    name: "probe.wgsl",
    code: "@compute @workgroup_size(1) fn main() { let p = WorldPoint(vec3i(0), vec3f(0.5)); if (world_sdf(p) < 0.0) { _ = world_material(p); } }",
  }], (m) => errors.push(m));
  assert(module !== null, errors.join("\n"));
  device.destroy();
});

Deno.test("results.json names every municipality, on the marker cell the table gives it", () => {
  const summary = JSON.parse(Deno.readTextFileSync("docs/sweden/results.json")) as {
    parties: { code: string; share: number; won: number }[];
    municipalities: { code: string; name: string; county: string; votes: number; marker: [number, number]; shares: Record<string, number> }[];
  };
  assert(summary.parties.length === PARTIES, `${summary.parties.length} parties in the summary`);
  assert(summary.parties.reduce((n, p) => n + p.won, 0) === MUNIS, "the municipalities won do not add up to all of them");
  assert(summary.municipalities.length === MUNIS, `${summary.municipalities.length} municipalities in the summary`);
  const markerOf = new Map<number, [number, number]>();
  for (const w of MARKERS) markerOf.set(w & 0x1ff, [(w >>> 9) & 0xff, (w >>> 17) & 0x1ff]);
  summary.municipalities.forEach((m, i) => {
    assert(m.name.length > 0 && m.county.endsWith("län"), `municipality ${i} is ${m.name} in ${m.county}`);
    const [col, row] = markerOf.get(i)!;
    assert(m.marker[0] === col && m.marker[1] === row, `${m.name}'s marker is at ${m.marker}, the table says ${col},${row}`);
    const total = Object.values(m.shares).reduce((a, b) => a + b, 0);
    assert(total > 90 && total <= 100.5, `${m.name}'s shares sum to ${total.toFixed(1)}%`);
  });
});

Deno.test("the projection puts Stockholm where Stockholm is, and the sea where it is not", () => {
  const cell = constant("SWEDEN_CELL");
  const x0 = constant("SWEDEN_X0");
  const z0 = constant("SWEDEN_Z0");
  // The constants docs/sweden/sweden-election.ts projects with.
  const LAT0 = 69.1, LON0 = 17.5, KM = 111.32;
  const at = (lat: number, lon: number): number => {
    const z = z0 + (LAT0 - lat) * KM;
    const x = (lon - LON0) * KM * Math.cos((lat * Math.PI) / 180);
    return muniAt(Math.floor((x - x0) / cell), Math.floor((z - z0) / cell));
  };
  const name = (muni: number): string => {
    const m = DATA.match(new RegExp(`^// ${muni - 1} (\\d{4}) ([^:]+):`, "m"));
    return m === null ? "?" : m[2];
  };
  const stockholm = at(59.33, 18.07);
  assert(name(stockholm) === "Stockholms kommun", `Stockholm's cell holds ${name(stockholm)}`);
  const kiruna = at(67.85, 20.22);
  assert(name(kiruna).startsWith("Kiruna"), `Kiruna's cell holds ${name(kiruna)}`);
  assert(at(58.0, 19.5) === 0, "the Baltic east of Gotland is not sea");
  assert(at(60.0, 5.0) === 0, "the Norwegian sea is not sea");
});
