// Sweden as the 2026 Riksdag election left it, drawn the way an election map is drawn.
// The country itself is a map in low relief: each municipality's land washed in a pale
// tone of the party that won it and raised with the votes cast there (as the square
// root, so a city is a hill and not a tower), the municipality borders inked on (the
// county borders wider), a sandy shallow along the coast and deeper water beyond, lakes
// where the boundaries leave holes. Over each
// municipality stands a stack of bubbles on a pin, one bubble per party from the
// biggest share at the bottom to the smallest at the top, each sized by the votes that
// party got there: area to the electorate, so Stockholm's stack is large and a northern
// municipality the size of a county is not, and the shape of a stack is the shape of
// the contest, a fat base under thin ones where one party ran away with it, near-equal
// bubbles where it was close. Nothing in the result is scaled to land area, which is
// what a choropleth gets wrong on a country whose people live in the south of it. One
// voxel is one kilometre, north is -Z. The data is sweden-data.wgsl, generated by
// sweden-election.ts beside it and prepended to this file in src/worlds/index.ts.
//
// The ground is a height field, blended between the cell centres so the relief rolls
// rather than steps, and the field is its vertical distance: that overestimates the
// true distance on a slope by the slope's secant, and the steepest slope the relief
// can have (VOTE_HEIGHT_MAX over one cell) is what WORLD_LIPSCHITZ covers. Bubbles are
// spheres and pins are boxes, exact distances both, and only the markers in the bands
// around the sample are tested, each stack first against the cylinder it stands in.
// Above the tallest stack and below the sea floor the field is exact, which is what
// lets the voxelizer skip the sky and the deep ground.
//
// At a far-field footprint a bubble narrower than a cell is drawn a cell wide rather
// than dropped (CLAUDE.md, `sample_footprint`), and a border is the whole cell it runs
// along rather than the voxel-wide line the voxelizer draws, so the map keeps both into
// the distance, which from the opening view is all of it. The pins go.

const WORLD_LIPSCHITZ: f32 = 8.0; // the secant of the steepest relief, see above

const SEA_LEVEL: f32 = 0.0;
const SEA_SHALLOW: f32 = -2.0; // the bed along the coast
const SEA_DEEP: f32 = -9.0; // and out at sea, before the swell in it
const LAND: f32 = 3.0; // the map's surface where nobody votes
// The relief: a municipality's land rises VOTE_HEIGHT voxels per square root of a vote
// cast there, to VOTE_HEIGHT_MAX. Stockholm's 614,000 votes make a hill of 28.
const VOTE_HEIGHT: f32 = 1.0 / 28.0;
const VOTE_HEIGHT_MAX: f32 = 30.0;
// A stack's first bubble floats HOVER above the map; each further one sits GAP above
// the last.
const HOVER: f32 = 5.0;
const GAP: f32 = 1.0;
// A bubble's radius is BUBBLE_MIN plus the square root of the party's votes there over
// BUBBLE_VOTES: Stockholm's largest is about 8 voxels, a village's smallest under 1.
const BUBBLE_MIN: f32 = 0.8;
const BUBBLE_VOTES: f32 = 3600.0; // 60 squared
const BUBBLE_MAX: f32 = 10.0; // no party anywhere reaches it; bounds the search
const STACK_MAX: f32 = 8.0 * (2.0 * BUBBLE_MAX + GAP);
// The bands of markers a sample has to test: those within a bubble's reach of its row.
const REACH_BANDS: i32 = 1; // a band is 4 rows of 4 km, and a bubble reaches 10
const TOP: f32 = LAND + VOTE_HEIGHT_MAX + HOVER + STACK_MAX;
const BORDER: f32 = 1.0; // border line width on the map, voxels
const COUNTY_BORDER: f32 = 2.0;

fn sweden_cell(x: f32, z: f32) -> vec2i {
  return vec2i(i32(floor((x - SWEDEN_X0) / SWEDEN_CELL)), i32(floor((z - SWEDEN_Z0) / SWEDEN_CELL)));
}

fn muni_winner(muni: u32) -> u32 {
  return SWEDEN_MUNI[muni - 1u] & 0xfu;
}

fn muni_county(muni: u32) -> u32 {
  return (SWEDEN_MUNI[muni - 1u] >> 24u) & 0x1fu;
}

fn party_block(party: u32) -> u32 {
  switch (party) {
    case 0u: { return BLOCK_PARTY_S; }
    case 1u: { return BLOCK_PARTY_M; }
    case 2u: { return BLOCK_PARTY_SD; }
    case 3u: { return BLOCK_PARTY_V; }
    case 4u: { return BLOCK_PARTY_C; }
    case 5u: { return BLOCK_PARTY_KD; }
    case 6u: { return BLOCK_PARTY_L; }
    default: { return BLOCK_PARTY_MP; }
  }
}

// The land of a municipality: the winning party's colour, washed out.
fn won_block(party: u32) -> u32 {
  switch (party) {
    case 0u: { return BLOCK_WON_S; }
    case 1u: { return BLOCK_WON_M; }
    case 2u: { return BLOCK_WON_SD; }
    case 3u: { return BLOCK_WON_V; }
    case 4u: { return BLOCK_WON_C; }
    case 5u: { return BLOCK_WON_KD; }
    case 6u: { return BLOCK_WON_L; }
    default: { return BLOCK_WON_MP; }
  }
}

fn vote_height(muni: u32) -> f32 {
  return min(VOTE_HEIGHT_MAX, sqrt(f32(SWEDEN_VOTES[muni - 1u])) * VOTE_HEIGHT);
}

// The ground at a cell's centre: the map raised by the votes, or the shallow bed for
// sea, which is what the land slopes down to at the coast.
fn cell_height(col: i32, row: i32) -> f32 {
  let m = sweden_muni_at(col, row);
  if (m == 0u) {
    return SEA_SHALLOW;
  }
  return LAND + vote_height(m);
}

// The ground under a point: the cell heights blended between the four nearest centres,
// so the relief rolls from one municipality into the next and down into the sea. Open
// sea, with no land at any of the four, is a deeper bed with a gentle swell in it, which
// is what gives it its patches of deeper water (`world_material`).
fn ground_height(p: WorldPoint, w: vec3f) -> f32 {
  let gx = (w.x - SWEDEN_X0) / SWEDEN_CELL - 0.5;
  let gz = (w.z - SWEDEN_Z0) / SWEDEN_CELL - 0.5;
  let c0 = i32(floor(gx));
  let r0 = i32(floor(gz));
  let fx = gx - f32(c0);
  let fz = gz - f32(r0);
  let land = sweden_muni_at(c0, r0) != 0u || sweden_muni_at(c0 + 1, r0) != 0u ||
    sweden_muni_at(c0, r0 + 1) != 0u || sweden_muni_at(c0 + 1, r0 + 1) != 0u;
  if (!land) {
    return SEA_DEEP + fbm2(p, 8u, 2u, 0.5) * 3.0; // wavelengths 256 and 128 voxels
  }
  let h0 = mix(cell_height(c0, r0), cell_height(c0 + 1, r0), fx);
  let h1 = mix(cell_height(c0, r0 + 1), cell_height(c0 + 1, r0 + 1), fx);
  return mix(h0, h1, fz);
}

fn bubble_radius(votes: f32) -> f32 {
  return BUBBLE_MIN + sqrt(votes / BUBBLE_VOTES);
}

// The nearest marker to a point: its signed distance (a bubble or the pin, whichever
// is nearer), the party of that bubble, and the municipality. Only the bands within a
// bubble's reach of the point's row are walked, and a stack's bubbles only when the
// cylinder the stack stands in is nearer than what has been found.
struct Marker {
  d: f32,
  party: u32,
  muni: u32, // index + 1, 0 when none is within reach
  bubble: bool, // the nearest part is a bubble, not the pin
}

fn nearest_marker(w: vec3f, cell: vec2i) -> Marker {
  var out = Marker(1e9, 0u, 0u, false);
  let band = cell.y / SWEDEN_BAND_ROWS;
  let b0 = max(0, band - REACH_BANDS);
  let b1 = min(SWEDEN_BANDS - 1, band + REACH_BANDS);
  // Below a cell a bubble is still drawn a cell wide, so its position survives the
  // distance; the pin, thinner than any cell, does not.
  let inflate = select(0.0, sample_footprint * 0.5, sample_footprint > 1.0);
  for (var b = b0; b <= b1; b++) {
    let end = SWEDEN_BAND_START[b + 1];
    for (var i = SWEDEN_BAND_START[b]; i < end; i++) {
      let m = SWEDEN_MARKERS[i];
      let index = m & 0x1ffu;
      let col = f32((m >> 9u) & 0xffu);
      let row = f32((m >> 17u) & 0x1ffu);
      let cx = SWEDEN_X0 + (col + 0.5) * SWEDEN_CELL;
      let cz = SWEDEN_Z0 + (row + 0.5) * SWEDEN_CELL;
      // The cylinder the whole stack stands in: no bubble can be nearer than this.
      let axis = length(w.xz - vec2f(cx, cz));
      let reach = max(BUBBLE_MAX, inflate);
      let within = max(axis - reach, max(LAND - w.y, w.y - TOP));
      if (within >= out.d) {
        continue;
      }
      let votes = f32(SWEDEN_VOTES[index]);
      var bottom = LAND + vote_height(index + 1u) + HOVER;
      for (var k = 0u; k < SWEDEN_STACK_WORDS * 2u; k++) {
        let word = SWEDEN_STACK[index * SWEDEN_STACK_WORDS + (k >> 1u)];
        let entry = select(word & 0xffffu, word >> 16u, (k & 1u) == 1u);
        let party = entry & 7u;
        let share = f32(entry >> 3u) * 0.001;
        let radius = max(bubble_radius(votes * share), inflate);
        let centre = vec3f(cx, bottom + radius, cz);
        let bubble = length(w - centre) - radius;
        if (bubble < out.d) {
          out = Marker(bubble, party, index + 1u, true);
        }
        bottom += 2.0 * radius + GAP;
      }
      if (sample_footprint <= 1.0) {
        // The pin: one voxel square, from the map up through the stack.
        let top = bottom - GAP;
        let foot = LAND + vote_height(index + 1u) - 1.0; // into the ground, so no gap on a slope
        let pin = sd_box(w - vec3f(cx, (foot + top) * 0.5, cz), vec3f(0.5, (top - foot) * 0.5, 0.5));
        if (pin < out.d) {
          out = Marker(pin, 0u, index + 1u, false);
        }
      }
    }
  }
  return out;
}

fn world_sdf(p: WorldPoint) -> f32 {
  let w = wp_f32(p);
  let y = w.y;
  if (y > TOP) {
    return y - TOP;
  }
  if (y < SEA_DEEP - 4.0) {
    return y - (SEA_DEEP - 3.0); // the nearest air is at least the deepest bed away, straight up
  }
  let cell = sweden_cell(w.x, w.z);
  let h = ground_height(p, w);
  let ground = y - h;
  // Water from the bed to sea level wherever the ground is under it. Solid to the field
  // like the ground, so the two meet at the shore without a gap; the material tells
  // them apart.
  let sea = max(y - SEA_LEVEL, h - y);
  var d = op_union(ground, sea);
  if (y > LAND - 1.0) {
    d = op_union(d, nearest_marker(w, cell).d);
  }
  return d;
}

// Whether a point on the map's surface is on a border: the west and north edges of a
// cell whose neighbour there is another municipality (or, wider, another county). At a
// voxel it is a line along the edge; at a far-field footprint it is the whole cell,
// which is the line's width at that distance anyway.
fn on_border(w: vec3f, cell: vec2i, muni: u32) -> bool {
  let coarse = sample_footprint > 1.0;
  let lx = w.x - (SWEDEN_X0 + f32(cell.x) * SWEDEN_CELL);
  let lz = w.z - (SWEDEN_Z0 + f32(cell.y) * SWEDEN_CELL);
  let west = sweden_muni_at(cell.x - 1, cell.y);
  let north = sweden_muni_at(cell.x, cell.y - 1);
  let county = muni_county(muni);
  if (west != 0u && west != muni) {
    let width = select(BORDER, COUNTY_BORDER, muni_county(west) != county);
    if (coarse || lx < width) {
      return true;
    }
  }
  if (north != 0u && north != muni) {
    let width = select(BORDER, COUNTY_BORDER, muni_county(north) != county);
    if (coarse || lz < width) {
      return true;
    }
  }
  return false;
}

fn world_material(p: WorldPoint) -> u32 {
  let w = wp_f32(p);
  let cell = sweden_cell(w.x, w.z);
  let muni = sweden_muni_at(cell.x, cell.y);
  let h = ground_height(p, w);
  // Solid above the ground is a marker or the sea. The sea's test is against the top
  // of what the sample stands for, not its centre: a far-field cell whose centre is in
  // the bed still has water in its upper half, and drawn as bed it is a sand patch on
  // the open sea.
  if ((w.y + sample_footprint * 0.5 >= h && muni == 0u) || w.y >= h) {
    if (w.y > LAND - 1.0) {
      let marker = nearest_marker(w, cell);
      if (marker.d <= 0.0) {
        return select(BLOCK_MAP_INK, party_block(marker.party), marker.bubble);
      }
    }
    return select(BLOCK_WATER, BLOCK_WATER_DEEP, h < SEA_DEEP);
  }
  if (muni == 0u) {
    return BLOCK_SAND; // the sea bed
  }
  // The map's top voxel carries the borders: at a far-field footprint, the top cell.
  if (h - w.y < 1.5 * sample_footprint && on_border(w, cell, muni)) {
    return BLOCK_MAP_INK;
  }
  return won_block(muni_winner(muni));
}
